### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by MPMachado** [Shopify/skeleton-theme#5]
When I try to start a yarn project, I'm getting this error:

yarn run v1.7.0
$ slate-tools start
/Users/miguel/Work/Development/Lab/Shopify/skeleton/slate.config.js:3
    dev: {resolve: {alias}},
                    ^

ReferenceError: alias is not defined
    at Object.<anonymous> (/Users/miguel/Work/Development/Lab/Shopify/skeleton/slate.config.js:3:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getSlateUserConfig (/Users/miguel/Work/Development/Lab/Shopify/skeleton/node_modules/@shopify/slate-config/index.js:67:12)
    at Object.<anonymous> (/Users/miguel/Work/Development/Lab/Shopify/skeleton/node_modules/@shopify/slate-config/index.js:5:52)
error Command failed with exit code 1.

**Comment by huguestennier** [comment]
Hey @MPMachado, I [opened a PR](https://github.com/Shopify/skeleton-theme/pull/6) to bump this theme to the new Slate version.

If you don't want to wait, you could bump the version in your `package.json` and try emptying your config file and see if `yarn start` works.

**Comment by MPMachado** [comment]
Already did and worked with no special configuration. 

Thanks
